server:
  port: 8089
  servlet:
    context-path: /ka
spring:
  profiles:
    active: dev
  #security
  security:
    user:
      name: admin
      password: 123456
    #redis
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10s
    lettuce:
      # 关闭超时时间
      shutdown-timeout: 1s
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 1000
        # 连接池中的最大空闲连接 默认 8
        max-idle: 300
        # 连接池中的最小空闲连接 默认 0
        min-idle: 3
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 1s
file:
  location: D:/demo/images/ #自定义上传文件本地保存路径
#日志配置
logging:
  config: classpath:logback-dev.xml
  level:
    com.dxj: debug
    org.springframework: warn
  file:
    path: /root/application/testApp/logs
knife4j:
  # 开启增强配置
  enable: true
#项目相关配置
keepAccounts:
  title: 记账接口文档
  description: 记账相关模块应用接口
  name: developer
  version: 1.0.0
  enabled-swagger: true
  #请求统一前缀
  pathMapping: /ka
#jwt配置
jwt:
  #jwt存储的请求头
  tokenHeader: Authorization
  #加密使用的密钥
  secret: C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeShVmYq3s6v9y$B&E)H@McQfTjWnZr4u7w
  #jwt超期时间（60*60*24）
  expiration: 604800
  #jwt负载中拿到开头
  tokenHead: Bearer