server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/keepAccountsDB?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  servlet:
    multipart:
      max-request-size: 100MB #设置总上传数据总大小
      max-file-size: 20MB #设置单个文件最大长度
file:
  location: D:/demo/images/ #自定义上传文件本地保存路径

mybatis-plus:
  #开启sql日志方便排查问题
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
